baseurl = "https://www.tao-yang.com"
title = "Tao Yang"
theme = "hugo-coder"


paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
    author = "Tao Yang"
    info = "L.A. based writer, actor, performer.  Former CollegeHumor Cast Member."
    description = "Tao Yang's personal website"
    title = "Tao Yang"
    keywords = "blog,personal,comedy,sketch,college humor,improv"
    avatarurl = "/images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"


    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css =["css/custom.css"]


# Social links
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/tyang209/"

[[params.social]]
    name = "Email"
    icon = "fas fa-envelope fa-2x"
    weight = 2
    url = "mailto:tyang209@gmail.com"

[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 3
    url = "https://www.instagram.com/tyang209"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin-in fa-2x"
    weight = 4
    url = "https://www.linkedin.com/in/tyang209/"    

[[params.social]]
    name = "IMDB"
    icon = "fab fa-imdb fa-2x"
    weight = 5
    url = "https://www.imdb.com/name/nm7032448/"      

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 3
    url  = "/posts/"
[[menu.main]]
    name = "Videos"
    weight = 1
    url = "/videos/"    
[[menu.main]]
    name = "Reels"
    weight = 2
    url = "/Reels/"     
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"            


# images
[[resources]]
  name = "soup"
  src = "images/tao_soup.jpg"