baseURL = "http://example.org/"
languageCode = "en-us"

baseurl = "www.tao-yang.com" # Hostname (and path) to the root.
title = "Tao Yang" # Site title.

theme = "coder-portfolio" # Set the theme.
languagecode = "en" # The site’s language code used to generate RSS.
defaultcontentlanguage = "en" # The default content language.

paginate = 20 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

disqusShortname = "yourdiscussshortname" # Enable or disable Disqus.

[params] # theme parameters
    author = "Tao Yang" # Author's name.
    info = "NYC Comedian" # Author's job title or info.
    description = "Tao Yang's personal website" # Site description.
    keywords = "blog,developer,personal" # Site keywords.
    avatarurl = "images/avatar.jpg" # Contain the path of the optionnal avatar in the static folder.
	aboutme = "Hey! I'm Tao and I'm a comedian in NYC. I'm currently a writer on the house sketch team, Presley, over at the Upright Citizen's Brigade Theater NY."
    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    snsShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Twitter"
    weight = 1
    url = "https://twitter.com/tyang209/"
[[params.social]]
    name = "Youtube"
    weight = 2
    url = "https://www.youtube.com/playlist?list=PLfUwzoe3jhKPZwoH4A0XM5HAmweIj5eUc"    
[[params.social]]
    name = "Email"
    weight = 3
    url = "mailto:tyang209@gmail.com"        


# Menu links
[[menu.main]]
    name = "Videos"
    weight = 1
    url  = "videos"